export const notableVenues: string[] = [
  "NeurIPS",
  "ICML",
  "ICLR",
  "CVPR",
  "ACL",
  "AAAI",
  "IJCAI",
  "Nature",
  "Science",
];

export const publications = [
  {
    year: 2025,
    title: "Advances in Transformer Architecture for Multi-Modal Learning",
    authors: "Smith, J., Johnson, A., Williams, R.",
    venue: "Neural Information Processing Systems (NeurIPS)",
    type: "Conference",
    award: "Best Paper Award",
    citations: 45,
  },
  {
    year: 2024,
    title: "Efficient Training Methods for Large Language Models",
    authors: "Chen, L., Davis, M., Anderson, K.",
    venue: "International Conference on Machine Learning (ICML)",
    type: "Conference",
    citations: 128,
  },
  {
    year: 2024,
    title:
      "Self-Supervised Learning for Computer Vision: A Comprehensive Survey",
    authors: "Smith, J., Lee, D., Rodriguez, E.",
    venue: "IEEE Transactions on Pattern Analysis and Machine Intelligence",
    type: "Journal",
    citations: 203,
  },
  {
    year: 2024,
    title: "Federated Learning with Privacy Guarantees",
    authors: "Patel, P., Wilson, J., Chen, M.",
    venue: "Conference on Computer Vision and Pattern Recognition (CVPR)",
    type: "Conference",
    citations: 87,
  },
  {
    year: 2023,
    title: "Neural Architecture Search: A Survey",
    authors: "Smith, J., Anderson, T., Kim, A.",
    venue: "Journal of Machine Learning Research",
    type: "Journal",
    citations: 456,
  },
  {
    year: 2023,
    title:
      "Advances in Natural Language Understanding Through Self-Supervised Learning",
    authors: "Smith, J., Anderson, K., Chen, L.",
    venue: "Association for Computational Linguistics (ACL)",
    type: "Conference",
    award: "Outstanding Paper",
    citations: 312,
  },
  {
    year: 2023,
    title: "Explainable AI for Medical Diagnosis",
    authors: "Lee, D., Garcia, M., Johnson, S.",
    venue: "Nature Medicine",
    type: "Journal",
    citations: 189,
  },
  {
    year: 2023,
    title: "Multi-Agent Reinforcement Learning in Complex Environments",
    authors: "Wilson, J., Rodriguez, E., Chen, M.",
    venue:
      "International Conference on Autonomous Agents and Multiagent Systems (AAMAS)",
    type: "Conference",
    citations: 94,
  },
  {
    year: 2022,
    title: "Graph Neural Networks for Knowledge Graph Completion",
    authors: "Wilson, J., Patel, P., Smith, J.",
    venue: "International Conference on Learning Representations (ICLR)",
    type: "Conference",
    citations: 267,
  },
  {
    year: 2022,
    title: "Fairness and Bias in Machine Learning: A Critical Review",
    authors: "Garcia, M., Smith, J., Anderson, K.",
    venue: "ACM Computing Surveys",
    type: "Journal",
    citations: 534,
  },
];
